name: Publish library

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - ".github/workflows/*"

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "publish"
  cancel-in-progress: true

jobs:
  publish:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Enable corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn

      - name: Test
        run: yarn test

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build

      - name: Check package version
        id: cpv
        uses: PostHog/check-package-version@v2

      - name: Publish
        if: steps.cpv.outputs.is-new-version == 'true'
        run: yarn npm publish
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Build pages
        if: steps.cpv.outputs.is-new-version == 'true'
        run: yarn build-storybook --output-dir public

      - name: Setup Pages
        if: steps.cpv.outputs.is-new-version == 'true'
        uses: actions/configure-pages@v4

      - name: Upload artifact
        if: steps.cpv.outputs.is-new-version == 'true'
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./public"

      - name: Deploy to GitHub Pages
        if: steps.cpv.outputs.is-new-version == 'true'
        id: deployment
        uses: actions/deploy-pages@v4
